chdir: /usr/share/ct-agent
user: ct
group: ct
environment: production
address: 0.0.0.0
port: 4567
pid: /tmp/ct-agent.pid
rackup: config/rackup.ru
log: log/agent.log
max_conns: 100
timeout: 30
max_persistent_conns: 100
daemonize: true
ssl: true
ssl_verify: true
ssl_key_file: '/var/lib/steamcannon/ssl/key.pem'
ssl_cert_file: '/var/lib/steamcannon/ssl/cert.pem'
